/*
    This Code Generated By DataManagerBuilder, Don't Modify It.
    Generate By UnityEditor:Build/Build DataList.
 * */
using System.IO;
using GameJson;
using System.Collections.Generic;

namespace Game
{
    public partial class DataManager
    {
        public JsonDataType<ViewConfig> viewConfig = new JsonDataType<ViewConfig>("viewconfig");
        public JsonDataType<GameString> gameString = new JsonDataType<GameString>("gamestring");
        public JsonDataType<PageData> pageDatas = new JsonDataType<PageData>("pagedata");
        public JsonDataType<GameBoxColor> boxColorConfig = new JsonDataType<GameBoxColor>("color3config");
        public JsonDataType<GameBoxColor> boxColor2Config = new JsonDataType<GameBoxColor>("color2config");
        public JsonDataType<BoxConfig> boxConfig = new JsonDataType<BoxConfig>("boxconfig");
        public JsonDataType<LevelConfig> levelConfig = new JsonDataType<LevelConfig>("levelconfig");
        public JsonDataType<PlayerConfig> playerConfig = new JsonDataType<PlayerConfig>("playerconfig");
        public JsonDataType<CameraConfig> cameraConfig = new JsonDataType<CameraConfig>("cameraconfig");
        public JsonDataType<SceneEditor.BuildConfig> buildConfg = new JsonDataType<SceneEditor.BuildConfig>("building");

        public void OnEnterScene(int mapID)
        {

        }

        public void OnLeaveScene()
        {
        }
    }
}
